### ISSUE TITLE
compatability with composer v2.0

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/extension-framework#6]
php bin/console uvdesk_extensions:configure-extensions

![Screenshot_276](https://user-images.githubusercontent.com/43210406/107345544-b1edad80-6ae9-11eb-9536-5a4664f0cd30.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

We have added composer 2 support. are you still facing this issue.
